theme: jekyll-theme-cayman
title: Corona Chart Neu-Isenburg
description: Interaktive Übersicht aktueller Daten zur Corona-Pandemie in Neu-Isenburg.
url: "https://corona.dsoko.de"
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-sitemap
lang: de
